// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AckRecordProto.proto

package com.wookler.server.river;

public final class AckRecordProto {
  private AckRecordProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AckRecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.wookler.server.river.AckRecord)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string messageId = 1;</code>
     */
    boolean hasMessageId();
    /**
     * <code>required string messageId = 1;</code>
     */
    java.lang.String getMessageId();
    /**
     * <code>required string messageId = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageIdBytes();

    /**
     * <code>required string blockId = 2;</code>
     */
    boolean hasBlockId();
    /**
     * <code>required string blockId = 2;</code>
     */
    java.lang.String getBlockId();
    /**
     * <code>required string blockId = 2;</code>
     */
    com.google.protobuf.ByteString
        getBlockIdBytes();

    /**
     * <code>required uint64 blockIndex = 3;</code>
     */
    boolean hasBlockIndex();
    /**
     * <code>required uint64 blockIndex = 3;</code>
     */
    long getBlockIndex();

    /**
     * <code>required uint64 sendTimestamp = 4;</code>
     */
    boolean hasSendTimestamp();
    /**
     * <code>required uint64 sendTimestamp = 4;</code>
     */
    long getSendTimestamp();

    /**
     * <code>required bool acked = 5;</code>
     */
    boolean hasAcked();
    /**
     * <code>required bool acked = 5;</code>
     */
    boolean getAcked();
  }
  /**
   * Protobuf type {@code com.wookler.server.river.AckRecord}
   */
  public static final class AckRecord extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.wookler.server.river.AckRecord)
      AckRecordOrBuilder {
    // Use AckRecord.newBuilder() to construct.
    private AckRecord(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AckRecord(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AckRecord defaultInstance;
    public static AckRecord getDefaultInstance() {
      return defaultInstance;
    }

    public AckRecord getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AckRecord(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              messageId_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              blockId_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              blockIndex_ = input.readUInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              sendTimestamp_ = input.readUInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              acked_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wookler.server.river.AckRecordProto.internal_static_com_wookler_server_river_AckRecord_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wookler.server.river.AckRecordProto.internal_static_com_wookler_server_river_AckRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wookler.server.river.AckRecordProto.AckRecord.class, com.wookler.server.river.AckRecordProto.AckRecord.Builder.class);
    }

    public static com.google.protobuf.Parser<AckRecord> PARSER =
        new com.google.protobuf.AbstractParser<AckRecord>() {
      public AckRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AckRecord(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AckRecord> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private java.lang.Object messageId_;
    /**
     * <code>required string messageId = 1;</code>
     */
    public boolean hasMessageId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string messageId = 1;</code>
     */
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          messageId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string messageId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BLOCKID_FIELD_NUMBER = 2;
    private java.lang.Object blockId_;
    /**
     * <code>required string blockId = 2;</code>
     */
    public boolean hasBlockId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string blockId = 2;</code>
     */
    public java.lang.String getBlockId() {
      java.lang.Object ref = blockId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          blockId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string blockId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBlockIdBytes() {
      java.lang.Object ref = blockId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        blockId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BLOCKINDEX_FIELD_NUMBER = 3;
    private long blockIndex_;
    /**
     * <code>required uint64 blockIndex = 3;</code>
     */
    public boolean hasBlockIndex() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint64 blockIndex = 3;</code>
     */
    public long getBlockIndex() {
      return blockIndex_;
    }

    public static final int SENDTIMESTAMP_FIELD_NUMBER = 4;
    private long sendTimestamp_;
    /**
     * <code>required uint64 sendTimestamp = 4;</code>
     */
    public boolean hasSendTimestamp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint64 sendTimestamp = 4;</code>
     */
    public long getSendTimestamp() {
      return sendTimestamp_;
    }

    public static final int ACKED_FIELD_NUMBER = 5;
    private boolean acked_;
    /**
     * <code>required bool acked = 5;</code>
     */
    public boolean hasAcked() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bool acked = 5;</code>
     */
    public boolean getAcked() {
      return acked_;
    }

    private void initFields() {
      messageId_ = "";
      blockId_ = "";
      blockIndex_ = 0L;
      sendTimestamp_ = 0L;
      acked_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMessageId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBlockId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBlockIndex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSendTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAcked()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMessageIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getBlockIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, blockIndex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(4, sendTimestamp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, acked_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMessageIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getBlockIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, blockIndex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, sendTimestamp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, acked_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.wookler.server.river.AckRecordProto.AckRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wookler.server.river.AckRecordProto.AckRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wookler.server.river.AckRecordProto.AckRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wookler.server.river.AckRecordProto.AckRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wookler.server.river.AckRecordProto.AckRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wookler.server.river.AckRecordProto.AckRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.wookler.server.river.AckRecordProto.AckRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.wookler.server.river.AckRecordProto.AckRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.wookler.server.river.AckRecordProto.AckRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wookler.server.river.AckRecordProto.AckRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wookler.server.river.AckRecordProto.AckRecord prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.wookler.server.river.AckRecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.wookler.server.river.AckRecord)
        com.wookler.server.river.AckRecordProto.AckRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wookler.server.river.AckRecordProto.internal_static_com_wookler_server_river_AckRecord_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wookler.server.river.AckRecordProto.internal_static_com_wookler_server_river_AckRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wookler.server.river.AckRecordProto.AckRecord.class, com.wookler.server.river.AckRecordProto.AckRecord.Builder.class);
      }

      // Construct using com.wookler.server.river.AckRecordProto.AckRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        messageId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        blockId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        blockIndex_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        sendTimestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        acked_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wookler.server.river.AckRecordProto.internal_static_com_wookler_server_river_AckRecord_descriptor;
      }

      public com.wookler.server.river.AckRecordProto.AckRecord getDefaultInstanceForType() {
        return com.wookler.server.river.AckRecordProto.AckRecord.getDefaultInstance();
      }

      public com.wookler.server.river.AckRecordProto.AckRecord build() {
        com.wookler.server.river.AckRecordProto.AckRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wookler.server.river.AckRecordProto.AckRecord buildPartial() {
        com.wookler.server.river.AckRecordProto.AckRecord result = new com.wookler.server.river.AckRecordProto.AckRecord(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageId_ = messageId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.blockId_ = blockId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.blockIndex_ = blockIndex_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sendTimestamp_ = sendTimestamp_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.acked_ = acked_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wookler.server.river.AckRecordProto.AckRecord) {
          return mergeFrom((com.wookler.server.river.AckRecordProto.AckRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wookler.server.river.AckRecordProto.AckRecord other) {
        if (other == com.wookler.server.river.AckRecordProto.AckRecord.getDefaultInstance()) return this;
        if (other.hasMessageId()) {
          bitField0_ |= 0x00000001;
          messageId_ = other.messageId_;
          onChanged();
        }
        if (other.hasBlockId()) {
          bitField0_ |= 0x00000002;
          blockId_ = other.blockId_;
          onChanged();
        }
        if (other.hasBlockIndex()) {
          setBlockIndex(other.getBlockIndex());
        }
        if (other.hasSendTimestamp()) {
          setSendTimestamp(other.getSendTimestamp());
        }
        if (other.hasAcked()) {
          setAcked(other.getAcked());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMessageId()) {
          
          return false;
        }
        if (!hasBlockId()) {
          
          return false;
        }
        if (!hasBlockIndex()) {
          
          return false;
        }
        if (!hasSendTimestamp()) {
          
          return false;
        }
        if (!hasAcked()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wookler.server.river.AckRecordProto.AckRecord parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wookler.server.river.AckRecordProto.AckRecord) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object messageId_ = "";
      /**
       * <code>required string messageId = 1;</code>
       */
      public boolean hasMessageId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string messageId = 1;</code>
       */
      public java.lang.String getMessageId() {
        java.lang.Object ref = messageId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            messageId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string messageId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageIdBytes() {
        java.lang.Object ref = messageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string messageId = 1;</code>
       */
      public Builder setMessageId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string messageId = 1;</code>
       */
      public Builder clearMessageId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageId_ = getDefaultInstance().getMessageId();
        onChanged();
        return this;
      }
      /**
       * <code>required string messageId = 1;</code>
       */
      public Builder setMessageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        messageId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object blockId_ = "";
      /**
       * <code>required string blockId = 2;</code>
       */
      public boolean hasBlockId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string blockId = 2;</code>
       */
      public java.lang.String getBlockId() {
        java.lang.Object ref = blockId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            blockId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string blockId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBlockIdBytes() {
        java.lang.Object ref = blockId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          blockId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string blockId = 2;</code>
       */
      public Builder setBlockId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        blockId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string blockId = 2;</code>
       */
      public Builder clearBlockId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        blockId_ = getDefaultInstance().getBlockId();
        onChanged();
        return this;
      }
      /**
       * <code>required string blockId = 2;</code>
       */
      public Builder setBlockIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        blockId_ = value;
        onChanged();
        return this;
      }

      private long blockIndex_ ;
      /**
       * <code>required uint64 blockIndex = 3;</code>
       */
      public boolean hasBlockIndex() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint64 blockIndex = 3;</code>
       */
      public long getBlockIndex() {
        return blockIndex_;
      }
      /**
       * <code>required uint64 blockIndex = 3;</code>
       */
      public Builder setBlockIndex(long value) {
        bitField0_ |= 0x00000004;
        blockIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 blockIndex = 3;</code>
       */
      public Builder clearBlockIndex() {
        bitField0_ = (bitField0_ & ~0x00000004);
        blockIndex_ = 0L;
        onChanged();
        return this;
      }

      private long sendTimestamp_ ;
      /**
       * <code>required uint64 sendTimestamp = 4;</code>
       */
      public boolean hasSendTimestamp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint64 sendTimestamp = 4;</code>
       */
      public long getSendTimestamp() {
        return sendTimestamp_;
      }
      /**
       * <code>required uint64 sendTimestamp = 4;</code>
       */
      public Builder setSendTimestamp(long value) {
        bitField0_ |= 0x00000008;
        sendTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 sendTimestamp = 4;</code>
       */
      public Builder clearSendTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sendTimestamp_ = 0L;
        onChanged();
        return this;
      }

      private boolean acked_ ;
      /**
       * <code>required bool acked = 5;</code>
       */
      public boolean hasAcked() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bool acked = 5;</code>
       */
      public boolean getAcked() {
        return acked_;
      }
      /**
       * <code>required bool acked = 5;</code>
       */
      public Builder setAcked(boolean value) {
        bitField0_ |= 0x00000010;
        acked_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool acked = 5;</code>
       */
      public Builder clearAcked() {
        bitField0_ = (bitField0_ & ~0x00000010);
        acked_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.wookler.server.river.AckRecord)
    }

    static {
      defaultInstance = new AckRecord(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.wookler.server.river.AckRecord)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wookler_server_river_AckRecord_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_wookler_server_river_AckRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024AckRecordProto.proto\022\030com.wookler.serv" +
      "er.river\"i\n\tAckRecord\022\021\n\tmessageId\030\001 \002(\t" +
      "\022\017\n\007blockId\030\002 \002(\t\022\022\n\nblockIndex\030\003 \002(\004\022\025\n" +
      "\rsendTimestamp\030\004 \002(\004\022\r\n\005acked\030\005 \002(\010B*\n\030c" +
      "om.wookler.server.riverB\016AckRecordProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_wookler_server_river_AckRecord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_wookler_server_river_AckRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_wookler_server_river_AckRecord_descriptor,
        new java.lang.String[] { "MessageId", "BlockId", "BlockIndex", "SendTimestamp", "Acked", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
